/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TeachersIndexImport } from './routes/teachers/index'
import { Route as StudentsIndexImport } from './routes/students/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TeachersIndexRoute = TeachersIndexImport.update({
  path: '/teachers/',
  getParentRoute: () => rootRoute,
} as any)

const StudentsIndexRoute = StudentsIndexImport.update({
  path: '/students/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsIndexImport
      parentRoute: typeof rootRoute
    }
    '/teachers/': {
      id: '/teachers/'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/students': typeof StudentsIndexRoute
  '/teachers': typeof TeachersIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/students': typeof StudentsIndexRoute
  '/teachers': typeof TeachersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/students/': typeof StudentsIndexRoute
  '/teachers/': typeof TeachersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/students' | '/teachers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/students' | '/teachers'
  id: '__root__' | '/' | '/students/' | '/teachers/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
  TeachersIndexRoute: typeof TeachersIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudentsIndexRoute: StudentsIndexRoute,
  TeachersIndexRoute: TeachersIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/students/",
        "/teachers/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/students/": {
      "filePath": "students/index.tsx"
    },
    "/teachers/": {
      "filePath": "teachers/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
