/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TeachersIndexImport } from './routes/teachers/index'
import { Route as StudentsIndexImport } from './routes/students/index'
import { Route as ParentsIndexImport } from './routes/parents/index'
import { Route as TeachersAddImport } from './routes/teachers/add'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TeachersIndexRoute = TeachersIndexImport.update({
  path: '/teachers/',
  getParentRoute: () => rootRoute,
} as any)

const StudentsIndexRoute = StudentsIndexImport.update({
  path: '/students/',
  getParentRoute: () => rootRoute,
} as any)

const ParentsIndexRoute = ParentsIndexImport.update({
  path: '/parents/',
  getParentRoute: () => rootRoute,
} as any)

const TeachersAddRoute = TeachersAddImport.update({
  path: '/teachers/add',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/teachers/add': {
      id: '/teachers/add'
      path: '/teachers/add'
      fullPath: '/teachers/add'
      preLoaderRoute: typeof TeachersAddImport
      parentRoute: typeof rootRoute
    }
    '/parents/': {
      id: '/parents/'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsIndexImport
      parentRoute: typeof rootRoute
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsIndexImport
      parentRoute: typeof rootRoute
    }
    '/teachers/': {
      id: '/teachers/'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/teachers/add': typeof TeachersAddRoute
  '/parents': typeof ParentsIndexRoute
  '/students': typeof StudentsIndexRoute
  '/teachers': typeof TeachersIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/teachers/add': typeof TeachersAddRoute
  '/parents': typeof ParentsIndexRoute
  '/students': typeof StudentsIndexRoute
  '/teachers': typeof TeachersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/teachers/add': typeof TeachersAddRoute
  '/parents/': typeof ParentsIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/teachers/': typeof TeachersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/teachers/add' | '/parents' | '/students' | '/teachers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/teachers/add' | '/parents' | '/students' | '/teachers'
  id:
    | '__root__'
    | '/'
    | '/teachers/add'
    | '/parents/'
    | '/students/'
    | '/teachers/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TeachersAddRoute: typeof TeachersAddRoute
  ParentsIndexRoute: typeof ParentsIndexRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
  TeachersIndexRoute: typeof TeachersIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TeachersAddRoute: TeachersAddRoute,
  ParentsIndexRoute: ParentsIndexRoute,
  StudentsIndexRoute: StudentsIndexRoute,
  TeachersIndexRoute: TeachersIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/teachers/add",
        "/parents/",
        "/students/",
        "/teachers/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/teachers/add": {
      "filePath": "teachers/add.tsx"
    },
    "/parents/": {
      "filePath": "parents/index.tsx"
    },
    "/students/": {
      "filePath": "students/index.tsx"
    },
    "/teachers/": {
      "filePath": "teachers/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
